/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.3-2-ge835b06f2d-20251119"
#endif /* AVUTIL_FFVERSION_H */
